# Model configuration and KD
model_name_or_path: meta-llama/Llama-3.2-1B-Instruct
teacher_model_name_or_path: meta-llama/Llama-3.1-8B-Instruct
kd_ratio: 0.5

# Training methodology
stage: sft
do_train: true
finetuning_type: lora
lora_rank: 128
lora_target: all

# Dataset configuration
dataset: limo
template: llama3
cutoff_len: 4096
max_samples: 1000
overwrite_cache: true
preprocessing_num_workers: 16

# Output configuration
output_dir: saves_limo/llama3-1b/lora/neo
logging_steps: 1
save_steps: 1000
plot_loss: true
overwrite_output_dir: true

# Training parameters
per_device_train_batch_size: 2
gradient_accumulation_steps: 16
learning_rate: 2.0e-04
num_train_epochs: 1.0
lr_scheduler_type: cosine
warmup_ratio: 0.1
bf16: true
ddp_timeout: 180000000
