#!/usr/bin/env python3
"""Turn results.csv into FINDINGS.md.

Reports, for every pair with results, the four Avg numbers and the two margins
that the experiment is actually about:

    shadow - rl_on_instruct     does grafting beat direct RL on the instruct model?
    shadow - rl_on_base         does grafting beat direct RL on the base model?

Also diffs `rl_on_base` and `rl_on_instruct` against the published numbers, since
a merged-model result means nothing if the harness cannot reproduce those first.

    python shadow_rl/aggregate.py --results shadow_rl/results.csv --out shadow_rl/FINDINGS.md
"""

from __future__ import annotations

import argparse
import csv
import os
import sys
from collections import defaultdict
from typing import Dict, Optional

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from pairs import (  # noqa: E402
    DATASETS, IN_DOMAIN, MODEL_ROLES, PAIRS, PAIRS_BY_ID, reference_avg, reference_for,
)

ROLE_LABEL = {
    "instruct_baseline": "W_I (untuned instruct)",
    "rl_on_instruct": "RL(W_I) (direct RL on instruct)",
    "rl_on_base": "RL(W_B) (direct RL on base)",
    "shadow": "W_shadow (ours)",
}

# Reproduction is called good when every dataset lands within this of the paper.
REPRO_TOL = 0.05


def fmt(x: Optional[float], places: int = 3, sign: bool = False) -> str:
    if x is None:
        return "--"
    return f"{x:+.{places}f}" if sign else f"{x:.{places}f}"


def load(path: str):
    if not os.path.exists(path):
        sys.exit(f"[fail] {path} not found. Run shadow_rl/evaluate.py first.")
    # results[pair_id][role][dataset] = em
    results: Dict[str, Dict[str, Dict[str, float]]] = defaultdict(lambda: defaultdict(dict))
    with open(path, newline="") as fh:
        for row in csv.DictReader(fh):
            with_search = str(row["with_search"]).lower() == "true"
            tag = "search" if with_search else "nosearch"
            pair_id = f"{row['algo']}-{tag}-{row['size']}-{row['version']}"
            results[pair_id][row["model_role"]][row["dataset"]] = float(row["em"])
    return results


def avg(per_dataset: Dict[str, float]) -> Optional[float]:
    """Average over the seven datasets; None unless all seven are present."""
    if not all(d in per_dataset for d in DATASETS):
        return None
    return sum(per_dataset[d] for d in DATASETS) / len(DATASETS)


def partial_avg(per_dataset: Dict[str, float]) -> Optional[float]:
    return sum(per_dataset.values()) / len(per_dataset) if per_dataset else None


def render(results, out_path: str) -> None:
    lines = [
        "# Shadow-FT weight grafting on matched RL checkpoint pairs",
        "",
        "`W_shadow = W_I + (RL(W_B) - W_B)` — the RL update learned on the base model,",
        "grafted onto the instruct backbone. No training; weight arithmetic plus evaluation.",
        "",
        "Metric is Exact Match over seven QA sets "
        f"({', '.join(sorted(IN_DOMAIN))} in-domain; the rest out-of-domain),",
        "scored with `verl/utils/reward_score/qa_em.py` from the official Search-R1 harness.",
        "",
    ]

    evaluated = [p for p in PAIRS if p.pair_id in results]
    if not evaluated:
        lines += [
            "## Status: no results yet",
            "",
            "`results.csv` has no rows, so there is nothing to report. The pipeline is in",
            "place and tested; what remains is GPU time. This file is regenerated by",
            "`shadow_rl/aggregate.py` every time `results.csv` grows.",
            "",
            "Order of work (see `shadow_rl/README.md`):",
            "",
            "1. Merge the 3B `R1-*` pair and confirm it loads and generates coherent text.",
            "2. Reproduce `rl_on_base` = 0.229 and `rl_on_instruct` = 0.224 on that pair.",
            "   **Do not proceed until the harness agrees** — a merged-model number is",
            "   uninterpretable if the two released checkpoints do not reproduce.",
            "3. Evaluate `W_shadow`. First real result.",
            "4. Repeat for the 7B `R1-*` pair (reference 0.276 / 0.271).",
            "5. Stand up BM25 retrieval and move to the GRPO pairs, 3B first.",
            "",
            "### Pairs awaiting evaluation",
            "",
            "| pair | algo | size | search | published RL(W_B) | published RL(W_I) |",
            "|---|---|---|---|---|---|",
        ]
        for p in PAIRS:
            lines.append(
                f"| `{p.pair_id}` | {p.algo} | {p.size} | "
                f"{'yes' if p.with_search else 'no'} | "
                f"{fmt(reference_avg(p, 'rl_on_base'))} | "
                f"{fmt(reference_avg(p, 'rl_on_instruct'))} |"
            )
        lines += [
            "",
            "Published averages are from the v0.1 paper; v0.2/v0.3 rows are ballpark only.",
            "",
        ]
        with open(out_path, "w") as fh:
            fh.write("\n".join(lines))
        print(f"[ok] wrote {out_path}  (no results yet)")
        return

    missing = [p.pair_id for p in PAIRS if p.pair_id not in results]

    # ---------------------------------------------------------------- summary
    lines += [
        "## Summary",
        "",
        "| pair | algo | size | search | W_I | RL(W_I) | RL(W_B) | **W_shadow** "
        "| shadow − RL(W_I) | shadow − RL(W_B) |",
        "|---|---|---|---|---|---|---|---|---|---|",
    ]
    for pair in evaluated:
        roles = results[pair.pair_id]
        a = {r: avg(roles.get(r, {})) for r in MODEL_ROLES}
        d_inst = (a["shadow"] - a["rl_on_instruct"]
                  if a["shadow"] is not None and a["rl_on_instruct"] is not None else None)
        d_base = (a["shadow"] - a["rl_on_base"]
                  if a["shadow"] is not None and a["rl_on_base"] is not None else None)
        lines.append(
            f"| `{pair.pair_id}` | {pair.algo} | {pair.size} | "
            f"{'yes' if pair.with_search else 'no'} | "
            f"{fmt(a['instruct_baseline'])} | {fmt(a['rl_on_instruct'])} | "
            f"{fmt(a['rl_on_base'])} | **{fmt(a['shadow'])}** | "
            f"{fmt(d_inst, sign=True)} | {fmt(d_base, sign=True)} |"
        )
    lines += ["", "Avg is over all seven datasets; `--` means that role is not yet complete.", ""]

    # ------------------------------------------------------- harness validation
    lines += [
        "## Harness validation",
        "",
        "The merged-model number is only meaningful if the harness reproduces the published",
        "numbers for the two released checkpoints. Δ is ours minus published; the v0.1 paper",
        "is the source, so v0.2/v0.3 rows are expected to agree only in the ballpark.",
        "",
        "| pair | role | ours | published | Δ | worst dataset Δ |",
        "|---|---|---|---|---|---|",
    ]
    for pair in evaluated:
        for role in ("rl_on_base", "rl_on_instruct"):
            got = results[pair.pair_id].get(role, {})
            ours, ref = avg(got), reference_avg(pair, role)
            if ours is None or ref is None:
                continue
            ref_per = reference_for(pair, role)
            worst_ds, worst_d = max(
                ((d, got[d] - ref_per[d]) for d in DATASETS if d in got and d in ref_per),
                key=lambda kv: abs(kv[1]),
                default=(None, None),
            )
            worst = f"{worst_ds} {fmt(worst_d, sign=True)}" if worst_ds else "--"
            lines.append(
                f"| `{pair.pair_id}` | {role} | {fmt(ours)} | {fmt(ref)} | "
                f"{fmt(ours - ref, sign=True)} | {worst} |"
            )
    lines += [
        "",
        f"A pair is safe to draw conclusions from when every dataset is within ~{REPRO_TOL:.2f}",
        "of the published number. The `instruct_baseline` row has no comparable published",
        "number: the paper's *direct inference* baseline uses a plain QA prompt, while we",
        "prompt every role with the same Search-R1 template so the four are comparable.",
        "",
    ]

    # ------------------------------------------------------------- per pair
    lines += ["## Per pair, per dataset", ""]
    for pair in evaluated:
        roles = results[pair.pair_id]
        lines += [
            f"### `{pair.pair_id}`",
            "",
            f"- {pair.algo.upper()}, {pair.size}, "
            f"{'with search' if pair.with_search else 'no search'}, {pair.version}",
            f"- base-side: `PeterJinGo/{pair.rl_base}`",
            f"- instruct-side: `PeterJinGo/{pair.rl_instruct}`",
            "",
            "| model | " + " | ".join(DATASETS) + " | **Avg** |",
            "|---" * (len(DATASETS) + 2) + "|",
        ]
        for role in MODEL_ROLES:
            per = roles.get(role, {})
            if not per:
                continue
            cells = " | ".join(fmt(per.get(d)) for d in DATASETS)
            a = avg(per)
            shown = fmt(a) if a is not None else f"{fmt(partial_avg(per))}*"
            label = ROLE_LABEL[role]
            if role == "shadow":
                label = f"**{label}**"
                shown = f"**{shown}**"
            lines.append(f"| {label} | {cells} | {shown} |")

        a_shadow = avg(roles.get("shadow", {}))
        a_inst = avg(roles.get("rl_on_instruct", {}))
        a_base = avg(roles.get("rl_on_base", {}))
        lines.append("")
        if a_shadow is None:
            lines += ["> `W_shadow` not evaluated yet for this pair.", ""]
        else:
            verdict = []
            if a_inst is not None:
                d = a_shadow - a_inst
                verdict.append(
                    f"- `shadow − rl_on_instruct` = **{fmt(d, sign=True)}** "
                    f"({'beats' if d > 0 else 'does not beat'} direct RL on instruct)"
                )
            if a_base is not None:
                d = a_shadow - a_base
                verdict.append(
                    f"- `shadow − rl_on_base` = **{fmt(d, sign=True)}** "
                    f"({'beats' if d > 0 else 'does not beat'} direct RL on base)"
                )
            lines += verdict + [""]

        stats_path = os.path.join(os.path.dirname(out_path), "merged", pair.pair_id,
                                  "shadow_merge_stats.json")
        if os.path.exists(stats_path):
            import json
            s = json.load(open(stats_path))
            flag = "" if s.get("sigma_in_range") else "  **outside the paper's 0.003–0.042 range**"
            lines += [
                f"- sigma (W_B vs W_I) = {s['sigma']:.5f}{flag}",
                f"- ||RL(W_B) − W_B|| / ||W_B|| = {s['rel_delta_base']:.5f}",
            ]
            if "rel_delta_instruct" in s:
                lines.append(f"- ||RL(W_I) − W_I|| / ||W_I|| = {s['rel_delta_instruct']:.5f}")
            lines.append("")

    if missing:
        lines += [
            "## Not yet evaluated",
            "",
            *(f"- `{m}`" for m in missing),
            "",
        ]

    lines += [
        "## Notes",
        "",
        "- `*` on an Avg marks a partial average — not all seven datasets are in yet.",
        "- Retrieval for the `SearchR1-*` pairs uses `PeterJinGo/wiki-18-bm25-index` for speed.",
        "  The paper uses a dense E5 index, so absolute numbers on the search pairs sit below",
        "  the published ones; the four roles share the index, so the comparison stays fair.",
        "- Decoding is greedy, so EM is reproducible across runs.",
        "",
    ]

    with open(out_path, "w") as fh:
        fh.write("\n".join(lines))
    print(f"[ok] wrote {out_path}  ({len(evaluated)}/{len(PAIRS)} pairs with results)")


def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--results", default="shadow_rl/results.csv")
    ap.add_argument("--out", default="shadow_rl/FINDINGS.md")
    args = ap.parse_args()
    render(load(args.results), args.out)


if __name__ == "__main__":
    main()
